### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ncovercash** [catalyst-app/Catalyst#2]
- [x] Stage One: Reach out, ensure the service would be useful, that there is a demand
- [ ] **Stage Two: Basic developement, put basic infastructure in place, brand initialization**
  - After this stage the site should be usable
  - Get logo done, get some initial popularity
  - Get that email list and whatnot going
  - FA forums
  - **See [basic features](#basic-features) below**
- [ ] Stage Three: Big time advertising, get some initial users
  - Advertise on e621/fa?
  - PM artists and whatnot, ask them to try it out
  - Incentives
    - Give featured status, maybe a badge thing, list on about us?
    - Early adopters
    - People who contribute and search out bugs
    - People who spread it all over the place
    - **Donators**
- [ ] Stage Four: Additional features
  - Take feature requests, act on them?
  - Maybe provide a meta-forum or something
  - **See [additional features](#additional-features) below**
- [ ] Stage Five: Optomization
  - If my servers don't explode then this could really go somewhere
  - **See [potential optimizations](#potential-optimizations) below**
- [ ] Stage Six: ???
- [ ] Stage Seven: Profit
  - Featured artists and stuff ($$$)
  - Plans for more features?
